add_newline = false

format = """
[╭─](bold) $username$hostname ─ $directory $git_branch$git_commit $git_status
[╰─](bold) $character """

[directory]
truncate_to_repo = false
format = "[$read_only]($read_only_style)[$path]($style)"
style = "cyan"
read_only = "?"
read_only_style = "red"

[character]
format = "$symbol"
success_symbol = "\\$"
error_symbol = "[\\$](red)"

[git_branch]
format = "[<$branch>]($style)"
style = "blue"
# truncation_length = 10
# truncation_symbol = ""

[git_commit]
style = "#FF7700"
format = "[\\($hash\\)]($style)"

[git_state]
disabled = true

[git_status]
conflicted = "[C](purple)\\($count\\)"
untracked = "[A](green)"
deleted = "[D](red)"
modified = "[M](red)"
staged = "[M](green)"
format = "$conflicted$deleted$modified$untracked$staged"

[hostname]
trim_at = ""
style = "yellow"
format = "@[$hostname]($style)"

[username]
style_root = "red"
style_user = "yellow"
show_always = true
format = "[$user]($style)"

